# Generated by Django 4.2.3 on 2023-07-28 05:24

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvtobusBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Avtobus raqami')),
                ('direction', models.CharField(max_length=40, verbose_name='Yonalishi nomi')),
                ('startend', models.CharField(max_length=500, verbose_name='Yonalish vaqti ')),
                ('sideways_time', models.FloatField(verbose_name='Yonalish davomligigi')),
                ('route_length', models.CharField(max_length=300, verbose_name='Yonalish uzunligi')),
                ('bus_brand', models.CharField(max_length=200, verbose_name='Avtobus markasi ')),
                ('place', models.CharField(max_length=300, verbose_name='Qoyish joyi')),
            ],
            options={
                'verbose_name': 'Avtobus vaqti',
                'verbose_name_plural': 'Avtobuslar vaqtilari',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AvtobusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avto_number', models.IntegerField()),
                ('start_place', models.CharField(max_length=200, verbose_name='Boshlangich bekat')),
                ('end_place', models.CharField(max_length=200, verbose_name='Oxirgi  bekat')),
                ('fast_time', models.CharField(max_length=200, verbose_name='Harakat vaqti')),
            ],
            options={
                'verbose_name': 'Avtobus malumotlar',
                'verbose_name_plural': 'Avtobuslar malumotlari ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AvtoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Avtobus yili')),
            ],
        ),
        migrations.CreateModel(
            name='AvtobusYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='nomi')),
                ('born_year', models.CharField(max_length=200, verbose_name='Chiqish yili')),
                ('size', models.CharField(max_length=100, verbose_name='Hajmi')),
                ('seat_count', models.CharField(max_length=100, verbose_name='Orindiq Soni')),
                ('number_direction', models.CharField(max_length=150, verbose_name='Yonalishlar soni ')),
                ('image', models.ImageField(upload_to='avtobus/')),
                ('content', tinymce.models.HTMLField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avtobus.avtocategory')),
            ],
            options={
                'verbose_name': 'Avtobus haqida ',
                'verbose_name_plural': 'Avtobuslar haqida',
                'ordering': ['id'],
            },
        ),
    ]
