# Generated by Django 4.2.3 on 2023-08-04 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avtobus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bus/')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='RegionName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=40)),
                ('in_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avtobus.regionname')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avtobus.modelcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BusOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, verbose_name='Odamlar sigdira oladigan  hajmi')),
                ('price', models.IntegerField()),
                ('images', models.ManyToManyField(blank=True, related_name='rasmlar', to='avtobus.busimage')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avtobus.modelcategory')),
            ],
        ),
    ]
