# Generated by Django 4.2.3 on 2023-08-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avtobus', '0002_busimage_modelcategory_regionname_orderpost_busorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busorder',
            old_name='name',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='orderpost',
            old_name='model',
            new_name='cat',
        ),
    ]
