# Generated by Django 4.2.3 on 2023-08-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avtobus', '0003_rename_name_busorder_cat_rename_model_orderpost_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avtobusyear',
            name='content',
        ),
    ]
