# Generated by Django 4.2.3 on 2023-08-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avtobus', '0004_remove_avtobusyear_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpost',
            old_name='in_city',
            new_name='city',
        ),
    ]
