# Generated by Django 4.2.3 on 2023-08-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avtobus', '0005_rename_in_city_orderpost_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpost',
            old_name='cat',
            new_name='cats',
        ),
    ]
