# Generated by Django 4.2.3 on 2023-08-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtobus', '0007_avtobusyear_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtobusyear',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Avtobus nomi '),
        ),
        migrations.AlterField(
            model_name='avtobusyear',
            name='seat_count',
            field=models.CharField(max_length=100, verbose_name='Orindiq soni'),
        ),
        migrations.AlterField(
            model_name='avtobusyear',
            name='size',
            field=models.CharField(max_length=100, verbose_name='odamlarni sigdira oladigan hajmi '),
        ),
    ]
