# Generated by Django 4.2.3 on 2023-08-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtobus', '0009_cardcategory_buscard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buscard',
            options={'ordering': ['id'], 'verbose_name': 'Karta tarifi', 'verbose_name_plural': 'Karta tariflari'},
        ),
        migrations.AddField(
            model_name='buscard',
            name='f_name',
            field=models.CharField(default=2, max_length=40, verbose_name='tarif rejasi'),
            preserve_default=False,
        ),
    ]
