# Generated by Django 4.2.3 on 2023-08-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtobus', '0010_alter_buscard_options_buscard_f_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buscard',
            name='cat1',
            field=models.ManyToManyField(blank=True, related_name='b_turlari', to='avtobus.cardcategory'),
        ),
        migrations.AddField(
            model_name='buscard',
            name='f_name1',
            field=models.CharField(default=2, max_length=300, verbose_name='tarif bolimi'),
            preserve_default=False,
        ),
    ]
