# Generated by Django 4.2.3 on 2023-08-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtobus', '0011_buscard_cat1_buscard_f_name1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardcategory',
            options={'ordering': ['id'], 'verbose_name': 'Karta Categoriya'},
        ),
        migrations.AlterField(
            model_name='buscard',
            name='cat',
            field=models.ManyToManyField(blank=True, related_name='k_turlar', to='avtobus.cardcategory'),
        ),
    ]
