# Generated by Django 4.2.3 on 2023-08-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtobus', '0012_alter_cardcategory_options_alter_buscard_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avtobusyear',
            options={'ordering': ['id'], 'verbose_name': 'Avtobus haqida', 'verbose_name_plural': 'Avtobuslar haqida'},
        ),
        migrations.AddField(
            model_name='avtobusyear',
            name='body',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
