# Generated by Django 4.2.3 on 2023-08-08 09:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtobus', '0014_alter_avtobusyear_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtobusyear',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avtobusyear',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
