# Generated by Django 4.2.3 on 2023-08-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avtobus', '0015_avtobusyear_content_alter_avtobusyear_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avtobusyear',
            name='body',
        ),
    ]
