# Generated by Django 4.2.3 on 2023-07-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nomi')),
                ('image', models.ImageField(upload_to='images/')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('views', models.ManyToManyField(blank=True, related_name='soni', to='news.ipmodel')),
            ],
            options={
                'verbose_name': 'yangilik',
                'verbose_name_plural': 'Yangilikla',
                'ordering': ['id'],
            },
        ),
    ]
