# Generated by Django 4.2.3 on 2023-08-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigNewsBaby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='baby/')),
                ('body', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=40)),
                ('leader_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Single page',
            },
        ),
        migrations.CreateModel(
            name='ImageNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bignew/')),
            ],
            options={
                'verbose_name': 'Rasmlar',
            },
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='img', to='news.imagenews'),
        ),
    ]
