# Generated by Django 4.2.3 on 2023-08-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_bignewsbaby_imagenews_remove_news_image_news_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_one',
            field=models.ImageField(default=2, upload_to='good/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bignewsbaby',
            name='name',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
