# Generated by Django 4.2.3 on 2023-08-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='xizmat nomi')),
                ('full_name', models.CharField(max_length=200, verbose_name='Lavozim egasi ismi')),
                ('title', models.TextField()),
                ('position', models.CharField(max_length=100, verbose_name='Lavozim darajasi')),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=30, verbose_name='tel nomer')),
            ],
        ),
    ]
