# Generated by Django 4.2.3 on 2023-08-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicename',
            name='image',
            field=models.ImageField(default=2, upload_to='ser/'),
            preserve_default=False,
        ),
    ]
