# Generated by Django 4.2.3 on 2023-08-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicename_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicename',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='ism'),
        ),
    ]
