# Generated by Django 4.2.3 on 2023-08-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_servicename_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicename',
            options={'ordering': ['id'], 'verbose_name': 'Xizmat', 'verbose_name_plural': 'Xizmatlar'},
        ),
    ]
