# Generated by Django 4.2.3 on 2023-07-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Rahbar nomi')),
                ('position', models.CharField(max_length=200, verbose_name='Lavozimi ')),
                ('tel_num', models.CharField(max_length=20, verbose_name='Telefon nomer')),
                ('faks', models.CharField(max_length=20, verbose_name='Qoshimcha faks')),
                ('image', models.ImageField(upload_to='leader/', verbose_name='leader rasmi ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email  nomi')),
                ('reception_time', models.CharField(max_length=400, verbose_name='Qabul vaqti ')),
            ],
            options={
                'verbose_name': 'Rahbar ',
                'verbose_name_plural': 'Rahbarlar',
                'ordering': ['id'],
            },
        ),
    ]
