# Generated by Django 4.2.3 on 2023-08-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='title',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
