# Generated by Django 4.2.3 on 2023-08-03 12:10

from django.db import migrations, models
import information.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Nomi')),
                ('file', models.FileField(upload_to='infor/', validators=[information.models.validate_file])),
            ],
        ),
    ]
