# Generated by Django 4.2.3 on 2023-07-28 05:42

import datetime
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.IntegerField(default=datetime.datetime.today, unique=True, validators=[user.models.validate_number])),
                ('verification_code', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=400, verbose_name='Toliq ism Familiya')),
                ('number', models.CharField(max_length=20, verbose_name='Telifon nomeri')),
                ('email', models.EmailField(max_length=254, validators=[user.models.validate_geeks_mail], verbose_name='Email manzili')),
                ('address', models.CharField(max_length=200, verbose_name='Manzil')),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('new', 'new'), ('middle', 'middle'), ('old', 'old')], default='new', max_length=7)),
                ('file', models.FileField(upload_to='hujjat/', validators=[user.models.validate_file])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['id'],
            },
        ),
    ]
