# Generated by Django 4.2.3 on 2023-07-28 07:06

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senduser',
            name='reference_number',
            field=models.IntegerField(unique=True, validators=[user.models.validate_number]),
        ),
    ]
