# Generated by Django 4.2.3 on 2023-07-28 11:40

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_senduser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senduser',
            name='reference_number',
            field=models.SmallIntegerField(unique=True, validators=[user.models.validate_number]),
        ),
    ]
