# Generated by Django 4.2.3 on 2023-07-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_senduser_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senduser',
            name='verification_code',
            field=models.CharField(max_length=10),
        ),
    ]
