# Generated by Django 4.2.3 on 2023-08-01 11:58

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_senduser_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senduser',
            name='reference_number',
            field=models.CharField(max_length=6, validators=[user.models.validate_number]),
        ),
    ]
