# Generated by Django 4.2.3 on 2023-08-02 09:11

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_senduser_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senduser',
            name='file',
            field=models.FileField(upload_to='', validators=[user.models.validate_file]),
        ),
    ]
