# Generated by Django 4.2.3 on 2023-08-02 11:10

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_senduser_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senduser',
            name='file',
            field=models.FileField(upload_to='new/', validators=[user.models.validate_file]),
        ),
    ]
