# Generated by Django 4.2.3 on 2023-07-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='hamkorlar/', verbose_name='Hamkorlar rasmi')),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=30, verbose_name='Telefon nomer')),
                ('url_name', models.CharField(max_length=4000, verbose_name='Web sayt silkasi')),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ['id'],
            },
        ),
    ]
